### ISSUE TITLE
Upgrade from 4.0.0 to 4.2.0 with docker compose installation

### ISSUE THREAD

**Issue by jackchuong** [wso2/docker-apim#487]
### Description

Hi all,
I'm trying WSO2 API Manager with docker compose, I have concerns about upgrading in future.
I started with docker.wso2.com/wso2am:4.0.0.191 , here my docker-compose.yml
```
version: '3.1'
services:
  jack:
    image: docker.wso2.com/wso2am:4.0.0.191
    container_name: jack
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 9443:9443
      - 8243:8243
      - 8280:8280
      - 9999:9999
      - 11111:11111
      - 8082:8082
    volumes:
      - ./deployment.toml:/home/wso2carbon/wso2am-4.0.0/repository/conf/deployment.toml
      - ./userstores:/home/wso2carbon/wso2am-4.0.0/repository/deployment/server/userstores
      - ./database:/home/wso2carbon/wso2am-4.0.0/repository/database
    restart: always
```
To be able to browse the default H2 database, I added the following configuration to the deployment.toml file
```
[database_configuration]
enable_h2_console = "true"
```
And it works fine, I can access to http://myserverip:8082 , browsing H2 databases and see they are 1.4.200 version.

I attempt to upgrade to 4.2.0 by changing image tag to "docker.wso2.com/wso2am:4.2.0" , but I get error when restart container
`Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "The write format 1 is smaller than the supported format 2 [2.1.210/5]" [50000-210]`
So I guess I have to migrate H2 database from 1.4.200 to 2.1.210 ?

I have a question about APIM 4.2.0 , when I start a fresh one (image: docker.wso2.com/wso2am:4.2.0) , the H2 console seem not working anymore, I cannot access to http://myserverip:8082 anymore , not error in log . Does anyone get same issue ?

I tried to migrate H2 database from 1.4.200 to 2.1.210
```
### Backup to zip files
java -cp h2-1.4.200.jar org.h2.tools.Script -url jdbc:h2:/<path to db>/WSO2AM_DB -user wso2carbon -password wso2carbon -script WSO2AM_DB.zip -options compression zip
java -cp h2-1.4.200.jar org.h2.tools.Script -url jdbc:h2:/<path to db>/WSO2CARBON_DB -user wso2carbon -password wso2carbon -script WSO2CARBON_DB.zip -options compression zip
java -cp h2-1.4.200.jar org.h2.tools.Script -url jdbc:h2:/<path to db>/WSO2MB_DB -user wso2carbon -password wso2carbon -script WSO2MB_DB.zip -options compression zip
java -cp h2-1.4.200.jar org.h2.tools.Script -url jdbc:h2:/<path to db>/WSO2METRICS_DB -user wso2carbon -password wso2carbon -script WSO2METRICS_DB.zip -options compression zip
java -cp h2-1.4.200.jar org.h2.tools.Script -url jdbc:h2:/<path to db>/WSO2SHARED_DB -user wso2carbon -password wso2carbon -script WSO2SHARED_DB.zip -options compression zip
### Restore
java -cp h2-2.1.210.jar org.h2.tools.RunScript -url jdbc:h2:/<path to db>/WSO2AM_DB -user wso2carbon -password wso2carbon -script WSO2AM_DB.zip -options compression zip FROM_1X
java -cp h2-2.1.210.jar org.h2.tools.RunScript -url jdbc:h2:/<path to db>/WSO2CARBON_DB -user wso2carbon -password wso2carbon -script WSO2CARBON_DB.zip -options compression zip FROM_1X
java -cp h2-2.1.210.jar org.h2.tools.RunScript -url jdbc:h2:/<path to db>/WSO2MB_DB -user wso2carbon -password wso2carbon -script WSO2MB_DB.zip -options compression zip FROM_1X
java -cp h2-2.1.210.jar org.h2.tools.RunScript -url jdbc:h2:/<path to db>/WSO2METRICS_DB -user wso2carbon -password wso2carbon -script WSO2METRICS_DB.zip -options compression zip FROM_1X
java -cp h2-2.1.210.jar org.h2.tools.RunScript -url jdbc:h2:/<path to db>/WSO2SHARED_DB -user wso2carbon -password wso2carbon -script WSO2SHARED_DB.zip -options compression zip FROM_1X
```

Then I start container with new image
```
version: '3.1'
services:
  jack:
    image: docker.wso2.com/wso2am:4.2.0
    container_name: jack
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 9443:9443
      - 8243:8243
      - 8280:8280
      - 9999:9999
      - 11111:11111
      - 8082:8082
    volumes:
      - ./deployment.toml:/home/wso2carbon/wso2am-4.2.0/repository/conf/deployment.toml
      - ./userstores:/home/wso2carbon/wso2am-4.2.0/repository/deployment/server/userstores
      - ./database:/home/wso2carbon/wso2am-4.2.0/repository/database
    restart: always
```

It started successfully but I get some error:
```
ERROR - APIManagerComponent Error while initializing the API manager component
org.wso2.carbon.apimgt.api.APIManagementException: Error while saving tenant conf to the Advanced configuration of the tenant carbon.super
...
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "AM_SYSTEM_CONFIGS" not found; SQL statement:
SELECT CONFIGURATION FROM AM_SYSTEM_CONFIGS WHERE ORGANIZATION = ? AND CONFIG_TYPE = ? [42102-210]
...
[2023-05-10 10:51:37,028] ERROR - CarbonTomcat Webapp StandardEngine[Catalina].StandardHost[localhost].StandardContext[/client-registration/v0.17] failed to deploy
[2023-05-10 10:51:37,029] ERROR - TomcatGenericWebappsDeployer Error while deploying webapp: StandardContext[client-registration#v0.17.war].File[/home/wso2carbon/wso2am-4.2.0/repository/deployment/server/webapps/client-registration#v0.17.war]
org.wso2.carbon.tomcat.CarbonTomcatException: Webapp failed to deploy
...
Caused by: java.lang.Exception: Webapp failed to deploy, Lifecycle state is STOPPED
        at org.wso2.carbon.tomcat.internal.CarbonTomcat.addWebApp(CarbonTomcat.java:307) ~[?:?]
```

And I lost secondary userstore (which is created before) when login to https://myserverip:9443/carbon .
How can I troubleshoot these issues ?
What is the properly way to upgrade WSO2 APIM running with docker compose ? 
What is the properly way to migrate  WSO2 APIM H2 databases from 1.4.200 to 2.1.210 ?
Please give me some advice, thank you very much.

### Affected Component

APIM

### Version

4.0.0

### Environment Details (with versions)

Ubuntu 22.04 with Docker version 20.10.21

### Suggested Labels

docker-compose, upgrade, H2 database migration
