### ISSUE TITLE
install with docker in network and change all localhost in variable to use specific dns name 

### ISSUE THREAD

**Issue by saber13812002** [wso2/docker-apim#511]
**Description:**
i install it but it redirect always to localhost. in login in other place like deploy and etc.

**Suggested Labels:**
how can i change all localhost to my dns name or any other standard way

**Affected Product Version:**
4.1 and 4.3

**OS, DB, other environment details and versions:**    
when use docker image and when use docker compose files

**Steps to reproduce:**

**Related Issues:**

docker compose file:

```
version: '3.7'

services:
  wso2am:

    image: wso2/wso2am:4.3.0
    
    container_name: wso2am
    ports:
      - "9443:9443"
      - "9763:9763"
      - "8243:8243"
      - "8280:8280"
    volumes:
      - wso2am_repository_deployment:/home/wso2carbon/wso2am/repository/deployment
      - ./config/deployment.toml:/home/wso2carbon/wso2am/repository/conf/deployment.toml
    environment:
      - JAVA_OPTS=-Dcarbon.bootstrap.timeout=300
      - TZ=UTC
    healthcheck:
      test: curl --fail http://192.168.100.37:9763/services/Version --silent | grep "Version" || exit 1
      interval: 1m
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  wso2am_repository_deployment:
    driver: local
```

deployment.toml
```
[server]
hostname = "192.168.100.37"
node_ip = "192.168.100.37"


[transport.https]
proxyPort = 9443
proxyHost = "192.168.100.37"

[transport.http]
proxyPort = 9763
proxyHost = "192.168.100.37"
```
